// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contracts/auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *CredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokensResponse) Reset() {
	*x = TokensResponse{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensResponse) ProtoMessage() {}

func (x *TokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensResponse.ProtoReflect.Descriptor instead.
func (*TokensResponse) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokensResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokensResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensRequest) Reset() {
	*x = RefreshTokensRequest{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensRequest) ProtoMessage() {}

func (x *RefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokensRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type StartResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResetPasswordRequest) Reset() {
	*x = StartResetPasswordRequest{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResetPasswordRequest) ProtoMessage() {}

func (x *StartResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*StartResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *StartResetPasswordRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type StartResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     string                 `protobuf:"bytes,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResetPasswordResponse) Reset() {
	*x = StartResetPasswordResponse{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResetPasswordResponse) ProtoMessage() {}

func (x *StartResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*StartResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *StartResetPasswordResponse) GetIsSuccess() string {
	if x != nil {
		return x.IsSuccess
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetCode     string                 `protobuf:"bytes,1,opt,name=reset_code,json=resetCode,proto3" json:"reset_code,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_contracts_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ResetPasswordRequest) GetResetCode() string {
	if x != nil {
		return x.ResetCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_contracts_auth_v1_auth_proto protoreflect.FileDescriptor

const file_contracts_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1ccontracts/auth/v1/auth.proto\x12\aauth.v1\"Q\n" +
	"\x12CredentialsRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"K\n" +
	"\x0eTokensResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\";\n" +
	"\x14RefreshTokensRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"<\n" +
	"\x19StartResetPasswordRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\";\n" +
	"\x1aStartResetPasswordResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\tR\tisSuccess\"Q\n" +
	"\x14ResetPasswordRequest\x12\x1d\n" +
	"\n" +
	"reset_code\x18\x01 \x01(\tR\tresetCode\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xfb\x02\n" +
	"\x04Auth\x12C\n" +
	"\vSetPassword\x12\x1b.auth.v1.CredentialsRequest\x1a\x17.auth.v1.TokensResponse\x12G\n" +
	"\rRefreshTokens\x12\x1d.auth.v1.RefreshTokensRequest\x1a\x17.auth.v1.TokensResponse\x12=\n" +
	"\x05Login\x12\x1b.auth.v1.CredentialsRequest\x1a\x17.auth.v1.TokensResponse\x12]\n" +
	"\x12StartResetPassword\x12\".auth.v1.StartResetPasswordRequest\x1a#.auth.v1.StartResetPasswordResponse\x12G\n" +
	"\rResetPassword\x12\x1d.auth.v1.ResetPasswordRequest\x1a\x17.auth.v1.TokensResponseB\x13Z\x11contracts/auth/v1b\x06proto3"

var (
	file_contracts_auth_v1_auth_proto_rawDescOnce sync.Once
	file_contracts_auth_v1_auth_proto_rawDescData []byte
)

func file_contracts_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_contracts_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_contracts_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_auth_v1_auth_proto_rawDesc), len(file_contracts_auth_v1_auth_proto_rawDesc)))
	})
	return file_contracts_auth_v1_auth_proto_rawDescData
}

var file_contracts_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contracts_auth_v1_auth_proto_goTypes = []any{
	(*CredentialsRequest)(nil),         // 0: auth.v1.CredentialsRequest
	(*TokensResponse)(nil),             // 1: auth.v1.TokensResponse
	(*RefreshTokensRequest)(nil),       // 2: auth.v1.RefreshTokensRequest
	(*StartResetPasswordRequest)(nil),  // 3: auth.v1.StartResetPasswordRequest
	(*StartResetPasswordResponse)(nil), // 4: auth.v1.StartResetPasswordResponse
	(*ResetPasswordRequest)(nil),       // 5: auth.v1.ResetPasswordRequest
}
var file_contracts_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.Auth.SetPassword:input_type -> auth.v1.CredentialsRequest
	2, // 1: auth.v1.Auth.RefreshTokens:input_type -> auth.v1.RefreshTokensRequest
	0, // 2: auth.v1.Auth.Login:input_type -> auth.v1.CredentialsRequest
	3, // 3: auth.v1.Auth.StartResetPassword:input_type -> auth.v1.StartResetPasswordRequest
	5, // 4: auth.v1.Auth.ResetPassword:input_type -> auth.v1.ResetPasswordRequest
	1, // 5: auth.v1.Auth.SetPassword:output_type -> auth.v1.TokensResponse
	1, // 6: auth.v1.Auth.RefreshTokens:output_type -> auth.v1.TokensResponse
	1, // 7: auth.v1.Auth.Login:output_type -> auth.v1.TokensResponse
	4, // 8: auth.v1.Auth.StartResetPassword:output_type -> auth.v1.StartResetPasswordResponse
	1, // 9: auth.v1.Auth.ResetPassword:output_type -> auth.v1.TokensResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_auth_v1_auth_proto_init() }
func file_contracts_auth_v1_auth_proto_init() {
	if File_contracts_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_auth_v1_auth_proto_rawDesc), len(file_contracts_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_contracts_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_contracts_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_contracts_auth_v1_auth_proto = out.File
	file_contracts_auth_v1_auth_proto_goTypes = nil
	file_contracts_auth_v1_auth_proto_depIdxs = nil
}
