// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contracts/users/v1/users.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор пользователя внутри системы
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Уникальный идентификатор пользователя в telegram
	TgId          string  `protobuf:"bytes,4,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	FirstName     string  `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	ChatId        string  `protobuf:"bytes,7,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_contracts_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_contracts_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	ChatId        string                 `protobuf:"bytes,6,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_contracts_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_contracts_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_contracts_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_contracts_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByTgIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIdRequest) Reset() {
	*x = GetUserByTgIdRequest{}
	mi := &file_contracts_users_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIdRequest) ProtoMessage() {}

func (x *GetUserByTgIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_users_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTgIdRequest) Descriptor() ([]byte, []int) {
	return file_contracts_users_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByTgIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByTgIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIdResponse) Reset() {
	*x = GetUserByTgIdResponse{}
	mi := &file_contracts_users_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIdResponse) ProtoMessage() {}

func (x *GetUserByTgIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_users_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByTgIdResponse) Descriptor() ([]byte, []int) {
	return file_contracts_users_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByTgIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_contracts_users_v1_users_proto protoreflect.FileDescriptor

const file_contracts_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1econtracts/users/v1/users.proto\x12\busers.v1\"\x93\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05tg_id\x18\x04 \x01(\tR\x04tgId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x06 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x17\n" +
	"\achat_id\x18\a \x01(\tR\x06chatIdB\f\n" +
	"\n" +
	"_last_name\"\x9c\x01\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\tR\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x17\n" +
	"\achat_id\x18\x06 \x01(\tR\x06chatIdB\f\n" +
	"\n" +
	"_last_name\"8\n" +
	"\x12CreateUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user\"&\n" +
	"\x14GetUserByTgIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x15GetUserByTgIdResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user2\xa2\x01\n" +
	"\x05Users\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.users.v1.CreateUserRequest\x1a\x1c.users.v1.CreateUserResponse\x12P\n" +
	"\rGetUserByTgId\x12\x1e.users.v1.GetUserByTgIdRequest\x1a\x1f.users.v1.GetUserByTgIdResponseB\x14Z\x12contracts/users/v1b\x06proto3"

var (
	file_contracts_users_v1_users_proto_rawDescOnce sync.Once
	file_contracts_users_v1_users_proto_rawDescData []byte
)

func file_contracts_users_v1_users_proto_rawDescGZIP() []byte {
	file_contracts_users_v1_users_proto_rawDescOnce.Do(func() {
		file_contracts_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_users_v1_users_proto_rawDesc), len(file_contracts_users_v1_users_proto_rawDesc)))
	})
	return file_contracts_users_v1_users_proto_rawDescData
}

var file_contracts_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contracts_users_v1_users_proto_goTypes = []any{
	(*User)(nil),                  // 0: users.v1.User
	(*CreateUserRequest)(nil),     // 1: users.v1.CreateUserRequest
	(*CreateUserResponse)(nil),    // 2: users.v1.CreateUserResponse
	(*GetUserByTgIdRequest)(nil),  // 3: users.v1.GetUserByTgIdRequest
	(*GetUserByTgIdResponse)(nil), // 4: users.v1.GetUserByTgIdResponse
}
var file_contracts_users_v1_users_proto_depIdxs = []int32{
	0, // 0: users.v1.CreateUserResponse.user:type_name -> users.v1.User
	0, // 1: users.v1.GetUserByTgIdResponse.user:type_name -> users.v1.User
	1, // 2: users.v1.Users.CreateUser:input_type -> users.v1.CreateUserRequest
	3, // 3: users.v1.Users.GetUserByTgId:input_type -> users.v1.GetUserByTgIdRequest
	2, // 4: users.v1.Users.CreateUser:output_type -> users.v1.CreateUserResponse
	4, // 5: users.v1.Users.GetUserByTgId:output_type -> users.v1.GetUserByTgIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_users_v1_users_proto_init() }
func file_contracts_users_v1_users_proto_init() {
	if File_contracts_users_v1_users_proto != nil {
		return
	}
	file_contracts_users_v1_users_proto_msgTypes[0].OneofWrappers = []any{}
	file_contracts_users_v1_users_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_users_v1_users_proto_rawDesc), len(file_contracts_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_users_v1_users_proto_goTypes,
		DependencyIndexes: file_contracts_users_v1_users_proto_depIdxs,
		MessageInfos:      file_contracts_users_v1_users_proto_msgTypes,
	}.Build()
	File_contracts_users_v1_users_proto = out.File
	file_contracts_users_v1_users_proto_goTypes = nil
	file_contracts_users_v1_users_proto_depIdxs = nil
}
