// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: contracts/ai-helper/v1/ai-helper.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIHelper_AskQuestion_FullMethodName = "/ai_helper.v1.AIHelper/AskQuestion"
)

// AIHelperClient is the client API for AIHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIHelperClient interface {
	AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error)
}

type aIHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewAIHelperClient(cc grpc.ClientConnInterface) AIHelperClient {
	return &aIHelperClient{cc}
}

func (c *aIHelperClient) AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionResponse)
	err := c.cc.Invoke(ctx, AIHelper_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIHelperServer is the server API for AIHelper service.
// All implementations must embed UnimplementedAIHelperServer
// for forward compatibility.
type AIHelperServer interface {
	AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error)
	mustEmbedUnimplementedAIHelperServer()
}

// UnimplementedAIHelperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIHelperServer struct{}

func (UnimplementedAIHelperServer) AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedAIHelperServer) mustEmbedUnimplementedAIHelperServer() {}
func (UnimplementedAIHelperServer) testEmbeddedByValue()                  {}

// UnsafeAIHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIHelperServer will
// result in compilation errors.
type UnsafeAIHelperServer interface {
	mustEmbedUnimplementedAIHelperServer()
}

func RegisterAIHelperServer(s grpc.ServiceRegistrar, srv AIHelperServer) {
	// If the following call pancis, it indicates UnimplementedAIHelperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIHelper_ServiceDesc, srv)
}

func _AIHelper_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIHelperServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIHelper_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIHelperServer).AskQuestion(ctx, req.(*AskQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIHelper_ServiceDesc is the grpc.ServiceDesc for AIHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_helper.v1.AIHelper",
	HandlerType: (*AIHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskQuestion",
			Handler:    _AIHelper_AskQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/ai-helper/v1/ai-helper.proto",
}
