// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contracts/ai-helper/v1/ai-helper.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionRequest) Reset() {
	*x = AskQuestionRequest{}
	mi := &file_contracts_ai_helper_v1_ai_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionRequest) ProtoMessage() {}

func (x *AskQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_ai_helper_v1_ai_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionRequest.ProtoReflect.Descriptor instead.
func (*AskQuestionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_ai_helper_v1_ai_helper_proto_rawDescGZIP(), []int{0}
}

func (x *AskQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AskQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionResponse) Reset() {
	*x = AskQuestionResponse{}
	mi := &file_contracts_ai_helper_v1_ai_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionResponse) ProtoMessage() {}

func (x *AskQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_ai_helper_v1_ai_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionResponse.ProtoReflect.Descriptor instead.
func (*AskQuestionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_ai_helper_v1_ai_helper_proto_rawDescGZIP(), []int{1}
}

func (x *AskQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_contracts_ai_helper_v1_ai_helper_proto protoreflect.FileDescriptor

const file_contracts_ai_helper_v1_ai_helper_proto_rawDesc = "" +
	"\n" +
	"&contracts/ai-helper/v1/ai-helper.proto\x12\fai_helper.v1\"0\n" +
	"\x12AskQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"-\n" +
	"\x13AskQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2^\n" +
	"\bAIHelper\x12R\n" +
	"\vAskQuestion\x12 .ai_helper.v1.AskQuestionRequest\x1a!.ai_helper.v1.AskQuestionResponseB\x18Z\x16contracts/ai_helper/v1b\x06proto3"

var (
	file_contracts_ai_helper_v1_ai_helper_proto_rawDescOnce sync.Once
	file_contracts_ai_helper_v1_ai_helper_proto_rawDescData []byte
)

func file_contracts_ai_helper_v1_ai_helper_proto_rawDescGZIP() []byte {
	file_contracts_ai_helper_v1_ai_helper_proto_rawDescOnce.Do(func() {
		file_contracts_ai_helper_v1_ai_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_ai_helper_v1_ai_helper_proto_rawDesc), len(file_contracts_ai_helper_v1_ai_helper_proto_rawDesc)))
	})
	return file_contracts_ai_helper_v1_ai_helper_proto_rawDescData
}

var file_contracts_ai_helper_v1_ai_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_ai_helper_v1_ai_helper_proto_goTypes = []any{
	(*AskQuestionRequest)(nil),  // 0: ai_helper.v1.AskQuestionRequest
	(*AskQuestionResponse)(nil), // 1: ai_helper.v1.AskQuestionResponse
}
var file_contracts_ai_helper_v1_ai_helper_proto_depIdxs = []int32{
	0, // 0: ai_helper.v1.AIHelper.AskQuestion:input_type -> ai_helper.v1.AskQuestionRequest
	1, // 1: ai_helper.v1.AIHelper.AskQuestion:output_type -> ai_helper.v1.AskQuestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_ai_helper_v1_ai_helper_proto_init() }
func file_contracts_ai_helper_v1_ai_helper_proto_init() {
	if File_contracts_ai_helper_v1_ai_helper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_ai_helper_v1_ai_helper_proto_rawDesc), len(file_contracts_ai_helper_v1_ai_helper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_ai_helper_v1_ai_helper_proto_goTypes,
		DependencyIndexes: file_contracts_ai_helper_v1_ai_helper_proto_depIdxs,
		MessageInfos:      file_contracts_ai_helper_v1_ai_helper_proto_msgTypes,
	}.Build()
	File_contracts_ai_helper_v1_ai_helper_proto = out.File
	file_contracts_ai_helper_v1_ai_helper_proto_goTypes = nil
	file_contracts_ai_helper_v1_ai_helper_proto_depIdxs = nil
}
