// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contracts/notifications/v1/notifications.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramNotifyRequest) Reset() {
	*x = TelegramNotifyRequest{}
	mi := &file_contracts_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramNotifyRequest) ProtoMessage() {}

func (x *TelegramNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramNotifyRequest.ProtoReflect.Descriptor instead.
func (*TelegramNotifyRequest) Descriptor() ([]byte, []int) {
	return file_contracts_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramNotifyRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TelegramNotifyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TelegramNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramNotifyResponse) Reset() {
	*x = TelegramNotifyResponse{}
	mi := &file_contracts_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramNotifyResponse) ProtoMessage() {}

func (x *TelegramNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramNotifyResponse.ProtoReflect.Descriptor instead.
func (*TelegramNotifyResponse) Descriptor() ([]byte, []int) {
	return file_contracts_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *TelegramNotifyResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_contracts_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_contracts_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	".contracts/notifications/v1/notifications.proto\x12\x10notifications.v1\"J\n" +
	"\x15TelegramNotifyRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"7\n" +
	"\x16TelegramNotifyResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess2t\n" +
	"\rNotifications\x12c\n" +
	"\x0eTelegramNotify\x12'.notifications.v1.TelegramNotifyRequest\x1a(.notifications.v1.TelegramNotifyResponseB\x1cZ\x1acontracts/notifications/v1b\x06proto3"

var (
	file_contracts_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_contracts_notifications_v1_notifications_proto_rawDescData []byte
)

func file_contracts_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_contracts_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_contracts_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_notifications_v1_notifications_proto_rawDesc), len(file_contracts_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_contracts_notifications_v1_notifications_proto_rawDescData
}

var file_contracts_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_notifications_v1_notifications_proto_goTypes = []any{
	(*TelegramNotifyRequest)(nil),  // 0: notifications.v1.TelegramNotifyRequest
	(*TelegramNotifyResponse)(nil), // 1: notifications.v1.TelegramNotifyResponse
}
var file_contracts_notifications_v1_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.v1.Notifications.TelegramNotify:input_type -> notifications.v1.TelegramNotifyRequest
	1, // 1: notifications.v1.Notifications.TelegramNotify:output_type -> notifications.v1.TelegramNotifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_notifications_v1_notifications_proto_init() }
func file_contracts_notifications_v1_notifications_proto_init() {
	if File_contracts_notifications_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_notifications_v1_notifications_proto_rawDesc), len(file_contracts_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_contracts_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_contracts_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_contracts_notifications_v1_notifications_proto = out.File
	file_contracts_notifications_v1_notifications_proto_goTypes = nil
	file_contracts_notifications_v1_notifications_proto_depIdxs = nil
}
