// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contracts/horoscope/v1/horoscope.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateOfBirth   string                 `protobuf:"bytes,1,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByDateRequest) Reset() {
	*x = GetByDateRequest{}
	mi := &file_contracts_horoscope_v1_horoscope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByDateRequest) ProtoMessage() {}

func (x *GetByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_horoscope_v1_horoscope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByDateRequest.ProtoReflect.Descriptor instead.
func (*GetByDateRequest) Descriptor() ([]byte, []int) {
	return file_contracts_horoscope_v1_horoscope_proto_rawDescGZIP(), []int{0}
}

func (x *GetByDateRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type GetByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByDateResponse) Reset() {
	*x = GetByDateResponse{}
	mi := &file_contracts_horoscope_v1_horoscope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByDateResponse) ProtoMessage() {}

func (x *GetByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_horoscope_v1_horoscope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByDateResponse.ProtoReflect.Descriptor instead.
func (*GetByDateResponse) Descriptor() ([]byte, []int) {
	return file_contracts_horoscope_v1_horoscope_proto_rawDescGZIP(), []int{1}
}

func (x *GetByDateResponse) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

var File_contracts_horoscope_v1_horoscope_proto protoreflect.FileDescriptor

const file_contracts_horoscope_v1_horoscope_proto_rawDesc = "" +
	"\n" +
	"&contracts/horoscope/v1/horoscope.proto\x12\fhoroscope.v1\"6\n" +
	"\x10GetByDateRequest\x12\"\n" +
	"\rdate_of_birth\x18\x01 \x01(\tR\vdateOfBirth\"3\n" +
	"\x11GetByDateResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction2Y\n" +
	"\tHoroscope\x12L\n" +
	"\tGetByDate\x12\x1e.horoscope.v1.GetByDateRequest\x1a\x1f.horoscope.v1.GetByDateResponseB\x18Z\x16contracts/horoscope/v1b\x06proto3"

var (
	file_contracts_horoscope_v1_horoscope_proto_rawDescOnce sync.Once
	file_contracts_horoscope_v1_horoscope_proto_rawDescData []byte
)

func file_contracts_horoscope_v1_horoscope_proto_rawDescGZIP() []byte {
	file_contracts_horoscope_v1_horoscope_proto_rawDescOnce.Do(func() {
		file_contracts_horoscope_v1_horoscope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_horoscope_v1_horoscope_proto_rawDesc), len(file_contracts_horoscope_v1_horoscope_proto_rawDesc)))
	})
	return file_contracts_horoscope_v1_horoscope_proto_rawDescData
}

var file_contracts_horoscope_v1_horoscope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_horoscope_v1_horoscope_proto_goTypes = []any{
	(*GetByDateRequest)(nil),  // 0: horoscope.v1.GetByDateRequest
	(*GetByDateResponse)(nil), // 1: horoscope.v1.GetByDateResponse
}
var file_contracts_horoscope_v1_horoscope_proto_depIdxs = []int32{
	0, // 0: horoscope.v1.Horoscope.GetByDate:input_type -> horoscope.v1.GetByDateRequest
	1, // 1: horoscope.v1.Horoscope.GetByDate:output_type -> horoscope.v1.GetByDateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_horoscope_v1_horoscope_proto_init() }
func file_contracts_horoscope_v1_horoscope_proto_init() {
	if File_contracts_horoscope_v1_horoscope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_horoscope_v1_horoscope_proto_rawDesc), len(file_contracts_horoscope_v1_horoscope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_horoscope_v1_horoscope_proto_goTypes,
		DependencyIndexes: file_contracts_horoscope_v1_horoscope_proto_depIdxs,
		MessageInfos:      file_contracts_horoscope_v1_horoscope_proto_msgTypes,
	}.Build()
	File_contracts_horoscope_v1_horoscope_proto = out.File
	file_contracts_horoscope_v1_horoscope_proto_goTypes = nil
	file_contracts_horoscope_v1_horoscope_proto_depIdxs = nil
}
