// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: contracts/horoscope/v1/horoscope.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Horoscope_GetByDate_FullMethodName = "/horoscope.v1.Horoscope/GetByDate"
)

// HoroscopeClient is the client API for Horoscope service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HoroscopeClient interface {
	GetByDate(ctx context.Context, in *GetByDateRequest, opts ...grpc.CallOption) (*GetByDateResponse, error)
}

type horoscopeClient struct {
	cc grpc.ClientConnInterface
}

func NewHoroscopeClient(cc grpc.ClientConnInterface) HoroscopeClient {
	return &horoscopeClient{cc}
}

func (c *horoscopeClient) GetByDate(ctx context.Context, in *GetByDateRequest, opts ...grpc.CallOption) (*GetByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByDateResponse)
	err := c.cc.Invoke(ctx, Horoscope_GetByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HoroscopeServer is the server API for Horoscope service.
// All implementations must embed UnimplementedHoroscopeServer
// for forward compatibility.
type HoroscopeServer interface {
	GetByDate(context.Context, *GetByDateRequest) (*GetByDateResponse, error)
	mustEmbedUnimplementedHoroscopeServer()
}

// UnimplementedHoroscopeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHoroscopeServer struct{}

func (UnimplementedHoroscopeServer) GetByDate(context.Context, *GetByDateRequest) (*GetByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByDate not implemented")
}
func (UnimplementedHoroscopeServer) mustEmbedUnimplementedHoroscopeServer() {}
func (UnimplementedHoroscopeServer) testEmbeddedByValue()                   {}

// UnsafeHoroscopeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HoroscopeServer will
// result in compilation errors.
type UnsafeHoroscopeServer interface {
	mustEmbedUnimplementedHoroscopeServer()
}

func RegisterHoroscopeServer(s grpc.ServiceRegistrar, srv HoroscopeServer) {
	// If the following call pancis, it indicates UnimplementedHoroscopeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Horoscope_ServiceDesc, srv)
}

func _Horoscope_GetByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoroscopeServer).GetByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Horoscope_GetByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoroscopeServer).GetByDate(ctx, req.(*GetByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Horoscope_ServiceDesc is the grpc.ServiceDesc for Horoscope service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Horoscope_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "horoscope.v1.Horoscope",
	HandlerType: (*HoroscopeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByDate",
			Handler:    _Horoscope_GetByDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/horoscope/v1/horoscope.proto",
}
